* Introduction

In [[https://parramatta.lizard.net/admin/lizard_nxt/clientconfiguration/1/change/][the Lizard admin]] a 'Client Configuration' can be configured for
the Parramatta Dashboard. It needs to have slug 'parramatta-dashboard'
and if a portal is set, the dashboard only works on that portal.

In the JSON field the app is configured, and this is passed to the
client from the [[https://parramatta.lizard.net/bootstrap/parramatta-dashboard/][/bootstrap/parramatta-dashboard/]] URL that is also used
to check the authentication status of the user; the URL and the
ClientConfiguration object are linked by having the same slug. The
JSON is in the "configuration" field of the API response.

This file documents the different options that can be set in the JSON.

The JSON is a dictionary with one mandatory key ("tiles") and one optional key
("periodHoursRelativeToNow").

Valid example with empty array of tiles:

    {
        "tiles": [],
        "periodHoursRelativeToNow": [-36, 6]
    }

* Configuration in Git

The JSON stored in the admin is hard to edit because all formatting is
lost. It can be made neater with online tools like
[[https://jsoneditoronline.org/][https://jsoneditoronline.org/]] , but formatted copies for staging and
production are also checked in (to review and document changes, and as
examples) in the configuration/ subdirectory of this
repository. Please keep those up to date when you make changes!

* tiles

This is an array of objects. There are several types of tile and they
each have their own configuration. Note that each tile in the
application has a small ("tile") version and a fullscreen version.

** Common keys

The following keys are shared by all tiles:

- "id": An integer, must be unique for each tile. To track which is currently selected.

- "title": string, the full (long) title of the tile that will be
  shown on the fullscreen view of the tile

- "shortTitle": *optional* string, will be used for the small versions
  of the tile if set, otherwise the normal title is used.

- "type": string, type of the tile that decides the other fields below.
  Currently one of "map", "timeseries", "statistics" or "external".

- "viewInLizardLink": *optional* string, if set then this is linked from the header
  above the fullscreen version of the tile.

** "map" tile

The map can show measuring stations, points and WMS layers, possibly of temporal rasters.

Keys:

- "assetTypes": optional, an array of assets types; but currently only ["measuringstation"] actually
  works. If set, all measurement stations in the map area are retrieved from the API and
  shown on the map.

- "bbox": optional, a 4-number array [westmost, southmost, eastmost, northmost] with WGS84 coordinates.
  Default if not set, see config.js:
  [150.9476776123047, -33.87831497192377, 151.0842590332031, -33.76800155639643]

- "datetime": optional, for temporal rasters. Objects for relative time that look like:

   {
     "type": "relative",
     "to": "now",  // or "start" or "end" (of a timeseries)
     "offset": 0, // Number of seconds before or after the "to" point
     "modulo": 300 // Optional number of seconds, only works for to: "now";
                   // Current time is rounded down to a multiple of this many seconds.
                   // Use so that the time only changes e.g. every five minutes.
   }

- "points": Optional array of objects for point markers.

  {
    "title": "This is a point",
    "geometry": {
       "type": "Point",
       "coordinates": [...]  // GeoJSON
    }
  }

- "rasters": Optional array of raster objects to show as WMS layer:

  {
    "uuid": string, UUID of the raster as in the API,
    "opacity": "0.5" // *string* with the opacity as a number
  }

- "wmsLayers": Optional array of extra WMS layers, for example:

  {
    "layers": "gauges",
    "format": "image/png",
    "url": "https://geoserver9.lizard.net/geoserver/parramatta/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1",
    "height": 256,
    "zindex": 1004,
    "width": 256,
    "srs": "EPSG:3857",
    "transparent": true
  }

** "timeseries" tile

These are charts of timeseries, they can have two sources:
intersections of a point geometry with a raster or timeseries objects
from the API.

Keys:

- "timeseries": array of timeseries UUIDs

- "colors": array of color codes for each timeseries

- "rasterIntersections": array of objects with the following keys:

  {
    "uuid": UUID of the raster,
    "geometry": {
      "type": "Point",
      "coordinates": [
        5.9223175048828125,
        52.15118665954508
      ]
    }
  }

It's not possible yet to set the color of charts of raster
intersections, they are a few shades of blue at the moment.

** "statistics" tile

Nothing can be configured here, so there should be exactly 1 of this tile in the list.

The app just retrieves all the alarms that the user has access to, assumes they're all
relevant, and shows statistics on them.

** "external" tile

This tile is for external web pages (must be https, and may have headers that prevent us
from using iframes, so not all pages work!).

It has two only two keys:

- "imageUrl": string, URL to the image to show in the tile
- "url": string of the web page to show in an iframe in the fullscreen version

* periodHoursRelativeToNow

If set, this is a 2-element array of integers. If not set, the default is [-24, 12].

It defines the period that is shown in charts, relative to now; so the
default shows charts going from 24 hours before now to 12 hours after
now.
