- hosts: all
  gather_facts: no
  remote_user: "{{ build_user }}"

  tasks:

  - name: download release
    get_url: url=https://github.com/nens/{{ repo_name }}/releases/download/{{ version }}/{{ version }}.zip dest=/tmp/{{ version }}.zip

  - name: rm old frontend
    file: path={{ deploy_path }} state=absent

  - name: mkdir
    file: path={{ deploy_path }} state=directory owner={{ build_user }}

  - name: unzip release
    # unarchive: src=/tmp/{{ version}}.zip dest=/var/www/frontend
    command: unzip /tmp/{{ version }}.zip -d {{ deploy_path }}

  - name: rm tmp zip
    file: path=/tmp/{{ version}}.zip state=absent
